FROM r-base:4.3.0

RUN apt-get update && apt-get install -y python3 python3-dev vim python3-pip
RUN apt-get install -y zlib1g zlib1g-dev libxml2-dev libssl-dev libcurl4-openssl-dev
RUN apt-get install -y sudo

#RUN apt-get install -y llvm
RUN useradd -ms /bin/bash ubuntu && adduser ubuntu sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
COPY requirements.txt /home/ubuntu/requirements.txt
RUN python3 -m pip install pip==22.3.1 --break-system-packages
RUN python3 -m pip install -r /home/ubuntu/requirements.txt

COPY ./ /home/ubuntu/SAPIEnS
workdir /home/ubuntu/SAPIEnS/imputation/scopen
RUN python3 setup.py install

ENV LANG="C.UTF-8"
WORKDIR /home/ubuntu/SAPIEnS
RUN Rscript install.R
user ubuntu
workdir /home/ubuntu


